" appearance
:colorscheme darkblue
:highlight Visual cterm=reverse ctermbg=NONE
syntax on
set relativenumber
set number
set scrolloff=5
set incsearch
" change cursor shape based on mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
" working with multiple files
set splitright
set splitbelow
" code folding
set foldmethod=indent
set foldlevelstart=99 "no closed folds w/ each new buffer"
nnoremap <space> za

" should speed up macros and large pastes
set lazyredraw

" typing behavior
set tabstop=4
set shiftwidth=4
set autoindent

" search behavior, ignore case when search all lowercase
set ignorecase
set smartcase
"\s to search word under cursor
:nnoremap <Leader>s :%s/\<<C-r><C-w>\>/

" File type specific settings
" python
autocmd FileType python
	\ setlocal tabstop=4 |
	\ setlocal softtabstop=4 |
	\ setlocal shiftwidth=4 |
	\ setlocal textwidth=79 |
	\ setlocal expandtab |
	\ setlocal autoindent |
	\ setlocal fileformat=unix
let g:ale_linters = {'python': ['flake8', 'mypy']}
" FIXERS HAD TO GO AFTER LOADING ALE...
" yaml
autocmd FileType yaml setlocal expandtab

" packages
set rtp+=~/dotfiles/linux-cli/fzf

" Put these lines at the very end of your vimrc file.
" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL

" python
let g:ale_fixers = {
\	'*': ['remove_trailing_lines', 'trim_whitespace'],
\	'python': ['black', 'isort']
\}
let g:ale_fix_on_save = 1
